myboot:
  #UserToken
  user-token:
    # UserToken密钥
    secret: 3d990d2276917dfac04467df11fff26d
    # UserToken过期时间
    expire: 30
    # UserToken重新颁发时间
    renewal: 20

  #生成唯一id
  snowflake:
    #数据中心id
    datacenterid: 1
    #工作机器id
    workerid: 1

  #Rocketmq
  rocketmq:
    namesrv-addr: 192.168.255.100:9876

logging:
  config: classpath:logback-boot-production.xml
  level:
    com.bookool.myboot.mapper: debug

spring:
  datasource:
    druid:
      url: jdbc:mariadb://192.168.255.100:3306/mymariadb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: mymariadb
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
      #初始化连接大小
      initial-size: 5
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 1000
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,wall
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
  #热部署
  devtools:
    livereload:
      #是否支持livereload
      enabled: false
    restart:
      #是否支持热部署
      enabled: false
  #AMQP
  rabbitmq:
    #rabbitmq连接参数
    host: 192.168.255.100
    port: 5672
    username: myboot
    password: 123456
    virtual-host: myboot
    #开启发送确认
    publisher-confirms: true
    #开启发送失败退回
    publisher-returns: true
    #开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  #Kafka
  kafka:
    bootstrap-servers: 192.168.255.100:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      # 此处配置方法搜索  java.time.Duration 在 yml properties 中的配置方法
      auto-commit-interval: PT1S
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
